version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/posgresql/data/
    env_file:
      - ./.env
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - web
  web:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./static_api/:/foodgram/foodgram_api/static_api/
      - ./media/:/foodgram/foodgram_api/media/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ./static_api/:/var/html/static_api/
      - ./media/:/var/html/media/

