# Generated by Django 2.2.19 on 2022-01-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211230_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default=1, upload_to='recipes/'),
            preserve_default=False,
        ),
    ]
